### ISSUE TITLE
请问生成frp-ssl证书是如何使用的？

### ISSUE THREAD

**Issue by Gabriel-six** [okxlin/ToolScript#2]
是要为frp客户端的本地ip生成证书吗？

**Comment by okxlin** [comment]
是开启tls加密传输用的，更安全

https://github.com/fatedier/frp?tab=readme-ov-file#tls

要服务端与客户端同时使用。

配置文件可以参考这个我写的

https://github.com/okxlin/appstore/tree/localApps/apps/frps

**Comment by Gabriel-six** [comment]
> 是开启tls加密传输用的，更安全
> 
> https://github.com/fatedier/frp?tab=readme-ov-file#tls
> 
> 要服务端与客户端同时使用。
> 
> 配置文件可以参考这个我写的
> 
> https://github.com/okxlin/appstore/tree/localApps/apps/frps

好的，感谢您回复。
可能我对该功能的了解有些误会。

我目前正在查询如何通过frp在外网以https方式访问部署在内网的web服务的问题，内网web服务已经自签发ssl证书，且内网https访问正常。但是不知道如何在外网也https访问。搜索资料一路找到您的项目这里来了。如果您对这个问题有所了解也欢迎赐教。

**Comment by okxlin** [comment]
内网已经https访问成功了，实际上你只要开启frp tcp类型的端口转发就行了

```
#frpc

[[proxies]]
name = "port_tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 443 #本地端口
remotePort = 1443  # 服务端端口
```

这样就能直接公网https://ip:1443端口访问了，

要域名的可以用Nginx反代，或者frp自身的`customDomains `设置

**Comment by Gabriel-six** [comment]
> 内网已经https访问成功了，实际上你只要开启frp tcp类型的端口转发就行了
> 
> ```
> #frpc
> 
> [[proxies]]
> name = "port_tcp"
> type = "tcp"
> localIP = "127.0.0.1"
> localPort = 443 #本地端口
> remotePort = 1443  # 服务端端口
> ```
> 
> 这样就能直接公网[https://ip:1443端口访问了，](https://ip:1443%E7%AB%AF%E5%8F%A3%E8%AE%BF%E9%97%AE%E4%BA%86%EF%BC%8C)
> 
> 要域名的可以用Nginx反代，或者frp自身的`customDomains `设置

好的，我尝试一下。
另外想问一下可以直接用frp的https类型端口转发吗？

**Comment by okxlin** [comment]
可以，直接https类型的就是我说的`customDomains`的设置

**Comment by Gabriel-six** [comment]
> 可以，直接https类型的就是我说的`customDomains`的设置

好的，感谢

**Comment by Gabriel-six** [comment]
> 内网已经https访问成功了，实际上你只要开启frp tcp类型的端口转发就行了
> 
> ```
> #frpc
> 
> [[proxies]]
> name = "port_tcp"
> type = "tcp"
> localIP = "127.0.0.1"
> localPort = 443 #本地端口
> remotePort = 1443  # 服务端端口
> ```
> 
> 这样就能直接公网[https://ip:1443端口访问了，](https://ip:1443%E7%AB%AF%E5%8F%A3%E8%AE%BF%E9%97%AE%E4%BA%86%EF%BC%8C)
> 
> 要域名的可以用Nginx反代，或者frp自身的`customDomains `设置

我已经设置https类型穿透，配置如下：
[[proxies]]
name = "web_https"
type = "https"
localIP = "127.0.0.1"
localPort = 80
customDomains = ["www.domain.com"]

但是浏览器访问域名显示：

The page you requested was not found.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

The server is powered by [frp](https://github.com/fatedier/frp).

Faithfully yours, frp.

frps中已设置vhostHTTPSPort = 443，且服务器相应端口已放行

**Comment by okxlin** [comment]
你这里错了

```
#frpc
localPort = 80
```
约定俗成的https端口默认443，http端口默认80

你用https不应该用80端口

**Comment by Gabriel-six** [comment]
> 你这里错了
> 
> ```
> #frpc
> localPort = 80
> ```
> 
> 约定俗成的https端口默认443，http端口默认80
> 
> 你用https不应该用80端口

好的，谢谢
